call code --install-extension Angular.ng-template
call code --install-extension CoenraadS.bracket-pair-colorizer
call code --install-extension EditorConfig.EditorConfig
call code --install-extension PKief.material-icon-theme
call code --install-extension PeterJausovec.vscode-docker
call code --install-extension Tyriar.sort-lines
call code --install-extension akamud.vscode-theme-onedark
call code --install-extension eg2.tslint
call code --install-extension johnpapa.Angular2
call code --install-extension ms-vscode.csharp
call code --install-extension ms-vscode.vs-keybindings
call code --install-extension msjsdiag.debugger-for-chrome
